// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urjqczcimjdueodjtynk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyanFjemNpbWpkdWVvZGp0eW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTM5NTMsImV4cCI6MjA3MDgyOTk1M30.8rVSHUVRkzn0j6sl4I9czbQ9j7HdAOhnrd3q3GF5jVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});